export const spokenLanguages = [
  "English",
  "Chinese",
  "Spanish",
  "Hindi",
  "French",
  "Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Indonesian",
  "Urdu",
  "German",
  "Japanese",
  "Swahili",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "Punjabi",
];
export const availability=["part", "full", "internship", "job"]